#!/usr/bin/env python3
import subprocess
import os
import sys
import argparse

def check_venv():
    """Ensures the script is running inside the virtual environment."""
    # sys.prefix != sys.base_prefix is the standard way to detect a venv in Python 3
    if not (sys.prefix != sys.base_prefix or 'VIRTUAL_ENV' in os.environ):
        print("\n[!] ERROR: Virtual environment not detected.")
        print("    This orchestrator requires the project venv to manage dependencies.")
        print("    Please run: source venv/bin/activate")
        sys.exit(1)

def main():
    # --- 0. Pre-Flight Check ---
    check_venv()
    parser = argparse.ArgumentParser(description="Generate 2x and 4x versions of a test clip for comparison.")
    parser.add_argument("test_clip", help="The test clip generated by extract_test_clip.py")
    args = parser.parse_args()

    if not os.path.exists(args.test_clip):
        print(f"Error: Clip {args.test_clip} not found.")
        sys.exit(1)

    # We run the actual pipeline twice on the small clip
    for scale in [2, 4]:
        print(f"\n--- Generating {scale}x Comparison Version ---")
        cmd = [
            "python3", "vhs_upscale_pipeline.py",
            args.test_clip,
            "--scale", str(scale),
            "--force"
        ]
        subprocess.run(cmd, check=True)

    print("\nProcessing complete. You can now run the 4-way comparison script.")

if __name__ == "__main__":
    main()
