#!/bin/bash
# ==============================================================================
# Script Name: capture_passthrough.sh v2 - Analog Passthrough Ingest
# Optimized for: Sony DCR-TRV330 acting as FireWire bridge for external VCR
# Source: VHS (or any analog source connected to the TRV330's A/V inputs)
# ==============================================================================
# CHANGE LOG:
#   v2 -- Applied three fixes from capture_tape.sh v32/v33/v34:
#         - v32 subline fix: awk now splits each \r-record on \n and processes
#           sublines independently. Fixes progress output stopping after the
#           first autosplit segment (e.g. after a VCR pause causes signal loss).
#         - v33 stat quoting: bitrate stat command wrapped in sh -c so shell
#           handles glob expansion safely when OUTPUT_DIR contains spaces.
#         - v34 multi-file audit: integrity audit now loops all AVI files with
#           per-file [OK]/[!!!]/[???] flags and a combined total summary,
#           instead of examining only the last file.
#
#   v1 -- Initial release.
# ==============================================================================
# PASSTHROUGH MODE NOTES:
#
# In this mode the TRV330 converts the incoming analog signal from an external
# VCR to a DV stream and passes it out over FireWire. The camera itself is NOT
# in playback mode and dvgrab cannot send AVC transport commands to control it.
# The external VCR must be started BEFORE this script is run.
#
# Timecode: Passthrough-mode timecodes are generated by the TRV330's internal
# clock at the moment of conversion, not by the source tape. They are valid
# wall-clock timestamps, not original recording dates.
#
# Date analysis: Because dates in the DV stream are the capture date (today),
# not original recording dates, the date analysis section from capture_tape.sh
# is omitted — it would only report today's date and is therefore meaningless.
#
# Progress: Frame count and elapsed wall-clock time are used for progress
# reporting. Since there is no tape position reference, the [PROGRESS] lines
# show elapsed capture time rather than a tape position estimate.
#
# Stall detection is still active and will warn if the incoming signal is lost.
# ==============================================================================
# CONFIGURATION REQUIRED:
# Set CAPTURE_ROOT to the absolute path where captured files will be stored.
# This directory must exist and be writable before running this script.
# Override at runtime with: -o /path/to/output
# ==============================================================================
#
# NOTE: The entire script body is wrapped in main() and called at the bottom.
# This causes bash to read and parse the complete script into memory before
# execution begins, so editing this file mid-run has no effect on the current
# capture session.
# ==============================================================================
set -uo pipefail

# ==============================================================================
# Dependency Preflight
# Fail early with a clear message rather than a cryptic error mid-capture.
# stdbuf is handled separately: it is strongly preferred (forces line-buffering
# so dvgrab's \r-separated records reach awk promptly) but not strictly
# required — without it, progress output may batch-flush rather than stream.
# ==============================================================================
for cmd in dvgrab ffprobe bc gawk; do
    command -v "$cmd" >/dev/null 2>&1 || {
        echo "[ERROR] Required command not found: $cmd"
        echo "        Install it and retry."
        exit 1
    }
done

if command -v stdbuf >/dev/null 2>&1; then
    DVGRAB_CMD=(stdbuf -oL dvgrab)
else
    echo "[WARNING] stdbuf not found — progress lines may buffer rather than stream."
    echo "          Install coreutils to suppress this warning."
    DVGRAB_CMD=(dvgrab)
fi

# ==============================================================================
# Configuration
# ==============================================================================
CAPTURE_ROOT="/mnt/video_capture/avi/captures"

# How often to emit a progress line during capture (seconds).
# In passthrough mode this is elapsed wall-clock time, not tape position.
PROGRESS_INTERVAL_SEC=60

# ==============================================================================
# main() — entire script body
# ==============================================================================
main() {

# ==============================================================================
# Usage / Help
# ==============================================================================
usage() {
    echo ""
    echo "Usage: $0 [-o OUTPUT_DIR] [-d DURATION] <SOURCE_ID> [DESCRIPTION]"
    echo ""
    echo "  -o OUTPUT_DIR  Optional. Override the default capture root."
    echo "                 Default: ${CAPTURE_ROOT}"
    echo "  -d DURATION    Optional. Stop automatically after this duration."
    echo "                 Format: HH:MM:SS or MM:SS or seconds (e.g. 37:00 or 2220)."
    echo "                 Useful when you know the source tape length and cannot"
    echo "                 monitor the capture. dvgrab stops cleanly at the limit."
    echo "  SOURCE_ID      Required. A short unique identifier for the source."
    echo "                 Spaces are allowed and will be converted to underscores."
    echo "  DESCRIPTION    Optional. Additional context appended to the filename."
    echo ""
    echo "Examples:"
    echo "  $0 VHS001"
    echo "     -> ${CAPTURE_ROOT}/VHS001_20250319_1430/VHS001_20250319_1430001.avi"
    echo ""
    echo "  $0 -d 37:00 VHS001 'Home Movies 1992'"
    echo "     Stops automatically after 37 minutes."
    echo ""
    echo "  $0 -d 1:32:00 BOX1_VHS03 'Christmas 1991'"
    echo "     Stops automatically after 1 hour 32 minutes."
    echo ""
    echo "PASSTHROUGH WORKFLOW:"
    echo "  1. Connect external VCR A/V out to TRV330 A/V in."
    echo "  2. Set TRV330 to VTR/VCR mode with A/V passthrough active."
    echo "  3. Cue VCR tape to the desired start point."
    echo "  4. Press PLAY on the VCR."
    echo "  5. Run this script immediately after."
    echo "  6. Press Ctrl+C to stop early, or let -d duration stop it automatically."
    echo "     Then press STOP on the VCR."
    echo ""
    echo "Notes:"
    echo "  - dvgrab cannot send commands to the camera in passthrough mode."
    echo "    The VCR must be started before this script is run."
    echo "  - Progress shows elapsed capture time (not tape position)."
    echo "  - Timecodes in the DV stream are today's wall-clock time."
    echo "    They are NOT original recording dates from the source tape."
    echo "  - Spaces are converted to underscores automatically."
    echo "  - Special characters are stripped for filesystem safety."
    echo ""
    echo "IMPORTANT: Default CAPTURE_ROOT is hardcoded in this script as:"
    echo "  ${CAPTURE_ROOT}"
    echo "  Edit the CAPTURE_ROOT variable at the top of the script to change it."
    echo ""
}

if [ "$#" -lt 1 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    usage
    [ "$#" -lt 1 ] && exit 1 || exit 0
fi

# ==============================================================================
# 1. Argument Parsing
# ==============================================================================
CAPTURE_DURATION=""   # empty means no limit; set via -d

while getopts ":o:d:" opt; do
    case $opt in
        o)
            CAPTURE_ROOT="$OPTARG"
            ;;
        d)
            CAPTURE_DURATION="$OPTARG"
            # Validate: accept HH:MM:SS, MM:SS, or plain seconds
            if ! echo "$CAPTURE_DURATION" | grep -qE '^([0-9]+:)?[0-9]{1,2}:[0-9]{2}$|^[0-9]+$'; then
                echo "[ERROR] -d duration must be HH:MM:SS, MM:SS, or seconds (got: $CAPTURE_DURATION)"
                usage
                exit 1
            fi
            ;;
        \?)
            echo "[ERROR] Unknown option: -$OPTARG"
            usage
            exit 1
            ;;
        :)
            echo "[ERROR] Option -$OPTARG requires an argument."
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ "$#" -lt 1 ]; then
    echo "[ERROR] SOURCE_ID is required."
    usage
    exit 1
fi

SOURCE_ID="$1"
EXTRA_DESC="${2:-}"

# ==============================================================================
# 2. Validate CAPTURE_ROOT
# ==============================================================================
if [ ! -d "$CAPTURE_ROOT" ]; then
    echo "[ERROR] CAPTURE_ROOT does not exist: $CAPTURE_ROOT"
    echo "        Create it with: mkdir -p $CAPTURE_ROOT"
    echo "        Or specify a different path with: -o /path/to/output"
    exit 1
fi
if [ ! -w "$CAPTURE_ROOT" ]; then
    echo "[ERROR] CAPTURE_ROOT is not writable: $CAPTURE_ROOT"
    _parent=$(dirname "$CAPTURE_ROOT")
    echo "        Check permissions with: ls -la \"$_parent\""
    exit 1
fi

# ==============================================================================
# 3. Configuration & Sanitization
# ==============================================================================
SAFE_ID=$(printf '%s' "$SOURCE_ID" | tr '[:space:]' '_' | tr -cd '[:alnum:]_-')
SAFE_DESC=$(printf '%s' "$EXTRA_DESC" | tr '[:space:]' '_' | tr -cd '[:alnum:]_-')

SESSION_DATE=$(date +%Y%m%d_%H%M)

if [[ -n "$SAFE_DESC" ]]; then
    BASE_NAME="${SAFE_ID}_${SAFE_DESC}_${SESSION_DATE}"
else
    BASE_NAME="${SAFE_ID}_${SESSION_DATE}"
fi

OUTPUT_DIR="${CAPTURE_ROOT}/${BASE_NAME}"
LOG_FILE="${OUTPUT_DIR}/${BASE_NAME}.log"

# ==============================================================================
# 4. Pre-flight: Directory Collision Check
# ==============================================================================
mkdir -p "$OUTPUT_DIR" || {
    echo "[ERROR] Failed to create output directory: $OUTPUT_DIR"
    exit 1
}
if [ "$(find "$OUTPUT_DIR" -mindepth 1 -print -quit 2>/dev/null)" ]; then
    echo "[WARNING] Output directory is not empty: $OUTPUT_DIR"
    echo "          A previous capture may exist. Continuing will mix files."
    read -p "Continue anyway? (y/n): " CONTINUE
    if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
        echo "Aborted. Remove or rename $OUTPUT_DIR and retry."
        exit 2
    fi
fi

# ==============================================================================
# 5. Hardware Pre-Check
# ==============================================================================
if ! ls /dev/fw* &>/dev/null && ! ls /dev/raw1394 &>/dev/null; then
    echo "[ERROR] FireWire device node not found."
    echo "        Is the TRV330 powered on and connected via FireWire?"
    echo "        Is it in VTR mode with A/V passthrough active?"
    exit 1
fi

echo "========================================================="
echo "PASSTHROUGH INGEST: $BASE_NAME"
echo "Output:  $OUTPUT_DIR"
echo "---------------------------------------------------------"
echo "CHECKLIST:"
echo " - TRV330 set to VTR mode with A/V passthrough active?"
echo " - External VCR connected to TRV330 A/V inputs?"
echo " - VCR cued and PLAY already pressed?"
echo " - Destination drive has ~35GB free per hour of source?"
echo "---------------------------------------------------------"
echo "[INFO] dvgrab will NOT command the camera in passthrough mode."
echo "       The VCR must already be playing before you proceed."
echo "---------------------------------------------------------"
read -p "Begin capture of incoming signal? (y/n): " PROCEED
if [[ ! "$PROCEED" =~ ^[Yy]$ ]]; then
    echo "Capture aborted by user."
    exit 2
fi

# ==============================================================================
# 6. Flag Configuration
# ==============================================================================
FLAGS=(
    --format dv2     # Type 2 AVI (standard for FFmpeg/AI pipeline)
    --size 0         # Single large file; no size-based splitting
    --autosplit      # Split on signal loss (e.g. VCR pause or tape end)
    --opendml        # Support files >4GB
    --showstatus     # Emit continuous progress lines for filtering below
    --noavc          # REQUIRED: disables AVC transport commands.
                     # Without this dvgrab will attempt to command the
                     # camera, which either hangs or produces errors since
                     # the TRV330 is in passthrough mode, not playback mode.
)

# Add --duration if the user specified -d. dvgrab accepts HH:MM:SS, MM:SS,
# or plain seconds and stops cleanly at the limit, closing the file properly.
if [[ -n "$CAPTURE_DURATION" ]]; then
    FLAGS+=(--duration "$CAPTURE_DURATION")
fi

echo "---------------------------------------------------------"
echo ">>> INITIALIZING DVGRAB IN PASSTHROUGH MODE..."
echo ">>> Capturing incoming signal from TRV330 A/V inputs."
if [[ -n "$CAPTURE_DURATION" ]]; then
    echo ">>> Auto-stop after: $CAPTURE_DURATION"
    echo ">>> Or press Ctrl+C to stop early."
else
    echo ">>> Press Ctrl+C to stop capture, then STOP on the VCR."
fi
echo "---------------------------------------------------------"

# ==============================================================================
# 7. Execution & Logging
# ==============================================================================
# PROGRESS_INTERVAL_SEC converted to a frame count at NTSC 29.97fps.
# Uses exact NTSC ratio 30000/1001 (same as capture_tape.sh).
PROGRESS_FRAMES=$(( PROGRESS_INTERVAL_SEC * 30000 / 1001 ))

OUTPUT_FILE_PREFIX="$OUTPUT_DIR/${BASE_NAME}"

# Seconds without frame progress before a stall warning is emitted.
# Stall most likely means signal loss (VCR paused, tape ended, cable issue).
STALL_TIMEOUT_SEC=15

# In passthrough mode the DV stream timecode is today's wall-clock time,
# not original recording dates from the source tape. We therefore track
# elapsed capture time using the script's own start time and frame count,
# and display that as the progress position instead.
#
# The awk record separator RS="\r" is required because dvgrab --showstatus
# uses carriage returns to overwrite its status line in place.
# DVGRAB_CMD prepends stdbuf -oL when available, forcing line-buffering so
# records reach awk promptly rather than accumulating in a block buffer.
#
# || true ensures the script continues to the Audit even if dvgrab
# exits non-zero (normal when Ctrl+C is pressed or signal is lost).
"${DVGRAB_CMD[@]}" "${FLAGS[@]}" "$OUTPUT_FILE_PREFIX" 2>&1 \
| awk -v interval="$PROGRESS_FRAMES" \
      -v outfile_prefix="$OUTPUT_FILE_PREFIX" \
      -v stall_sec="$STALL_TIMEOUT_SEC" '
    BEGIN {
        RS                 = "\r"
        last_printed       = -1
        last_frame_seen    = -1
        last_progress_time = systime()
        capture_start_time = systime()
    }
    {
        # RS="\r" splits on carriage returns before any rule runs.
        # Each record may still contain \n-embedded sublines: dvgrab
        # emits a \n-terminated filename announcement when opening a new
        # autosplit segment, mixed into the otherwise \r-delimited stream.
        # This creates a single \r-record containing two logical lines
        # joined by \n. Processing $0 as a blob causes the frame-count
        # regex to miss the status portion, stopping progress output for
        # the rest of the capture. Split each record into sublines and
        # handle each one independently to avoid this.
        n = split($0, sublines, "\n")
        for (i = 1; i <= n; i++) {
            line = sublines[i]

            # Strip control characters (including BEL 0x07) and whitespace.
            gsub(/[\x00-\x1F]/, "", line)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
            if (line == "") continue

            # Critical and lifecycle lines — pass through with banners for errors.
            if (line ~ /(damaged|missing|invalid|[Ee]rror|Warning:|Autosplit|Capture Start|Capture Stop)/) {
                if (line ~ /(damaged|missing|invalid|[Ee]rror|Warning:)/) {
                    if (!(line in warned)) {
                        warned[line] = 1
                        print "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
                        print "!!! " line
                        print "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
                        fflush()
                    }
                } else {
                    print line; fflush()
                }
                continue
            }

            # Progress lines: track frame count, apply stall detection and
            # interval sampling. Display elapsed wall-clock capture time
            # rather than frame-derived tape position — in passthrough mode
            # the two should match but elapsed time is more meaningful since
            # there is no tape position reference from the source VCR.
            if (match(line, /([0-9]+)[[:space:]]+frames/, m)) {
                frame_count = m[1]
                now         = systime()

                # Stall detection: no frame progress for stall_sec seconds.
                # last_frame_seen >= 0 skips the comparison on the very first
                # record (before a baseline exists); frame counts start at 0
                # so -1 can never match, but the guard makes the intent explicit.
                # == rather than < because frame counts are monotonically
                # increasing — dvgrab briefly repeats a count at autosplit
                # boundaries but never goes backwards, so equality is the
                # correct stall signal and < would never be true in normal use.
                # The time gate is the outer condition so a transient repeat at
                # an autosplit boundary does not fire the banner prematurely —
                # only a sustained stall triggers it.
                # In passthrough mode a stall most likely means signal loss
                # (VCR paused, tape ended, or A/V cable disconnected).
                if (last_frame_seen >= 0 && frame_count == last_frame_seen && now - last_progress_time >= stall_sec) {
                    printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
                    printf "!!! WARNING: Signal lost or stalled — no frame progress for ~%ds\n", now - last_progress_time
                    printf "!!!          Check VCR is still playing and A/V cable is connected.\n"
                    printf "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
                    fflush()
                    last_progress_time = now
                } else if (frame_count != last_frame_seen) {
                    last_progress_time = now
                }
                last_frame_seen = frame_count

                # Sample at interval, always print first line.
                if (last_printed < 0 || frame_count - last_printed >= interval) {

                    # Elapsed capture time from this script'\''s start (wall clock).
                    elapsed_sec = now - capture_start_time
                    h   = int(elapsed_sec / 3600)
                    m_  = int((elapsed_sec % 3600) / 60)
                    s   = elapsed_sec % 60

                    # Real-time bitrate from cumulative size of ALL segment files.
                    # Wrapped in sh -c so the shell handles glob expansion safely
                    # even when OUTPUT_DIR contains spaces (v33 fix).
                    bitrate_mbps = "N/A"
                    if (elapsed_sec > 5) {
                        filesize = 0
                        cmd = "sh -c 'stat -c%s \"" outfile_prefix "\"*.avi 2>/dev/null'"
                        while ((cmd | getline sz) > 0) filesize += sz
                        close(cmd)
                        if (filesize > 0)
                            bitrate_mbps = sprintf("%.2f", (filesize * 8) / elapsed_sec / 1000000)
                    }

                    # Strip the timecode and date fields from the status line.
                    # In passthrough mode these are today'\''s wall-clock values
                    # from the TRV330 — they are not original recording dates
                    # and add no useful information for the operator.
                    clean = line
                    gsub(/ timecode [^ ]+/, "", clean)
                    gsub(/ date [0-9]+\.[0-9]+\.[0-9]+ [0-9:]+/, "", clean)

                    printf "[ELAPSED %d:%02d:%02d | %s Mbps] %s\n", h, m_, s, bitrate_mbps, clean
                    fflush()
                    last_printed = frame_count
                }
                continue
            }

            # Pass through everything else (device init messages, etc.)
            print line; fflush()
        }
    }
' | tee "$LOG_FILE" || true

# ==============================================================================
# 8. Post-Capture Integrity Audit
# ==============================================================================
# Passthrough captures are normally a single file, but dvgrab will autosplit
# on signal loss (VCR pause, tape end, cable hiccup). We audit every file so
# that a corrupted first segment is never silently skipped.
# ==============================================================================
printf '\a'
echo "---------------------------------------------------------"
echo "RUNNING DATA INTEGRITY AUDIT..."

shopt -s nullglob
AVI_FILES=("$OUTPUT_DIR"/*.avi)
shopt -u nullglob

if [ "${#AVI_FILES[@]}" -eq 0 ]; then
    echo "[ERROR] No AVI file was generated. Check $LOG_FILE" | tee -a "$LOG_FILE"
    echo "        Possible causes:"
    echo "          - TRV330 was not in A/V passthrough mode"
    echo "          - VCR was not playing before capture started"
    echo "          - FireWire signal was not established"
    exit 1
fi

TOTAL_DURATION_SEC=0
TOTAL_SIZE_BYTES=0
WARN_COUNT=0
FFPROBE_FALLBACK_NOTED=0

{
    echo "DATA INTEGRITY AUDIT: $BASE_NAME"
    echo "Generated: $(date)"
    echo "Files: ${#AVI_FILES[@]}"
    echo "---------------------------------------------------------"

    for AVI_FILE in $(printf '%s\n' "${AVI_FILES[@]}" | sort); do

        STATS=$(ffprobe -v error -show_entries format=duration,bit_rate \
            -of default=noprint_wrappers=1 "$AVI_FILE" 2>&1 \
            | grep -E '^(duration|bit_rate)')

        BITRATE=$(echo "$STATS" | grep "^bit_rate" | cut -d= -f2 || echo "N/A")
        DURATION=$(echo "$STATS" | grep "^duration" | cut -d= -f2 || echo "0")

        BITRATE="${BITRATE:-N/A}"
        DURATION="${DURATION:-0}"

        FILE_SIZE=$(stat -c%s "$AVI_FILE")
        TOTAL_SIZE_BYTES=$(( TOTAL_SIZE_BYTES + FILE_SIZE ))

        # Guard: ffprobe often returns N/A for bit_rate on DV/AVI containers.
        # Fall back to manual calculation from file size and duration.
        if [[ "$BITRATE" == "N/A" || "$BITRATE" == "0" ]]; then
            if [[ "$DURATION" == "0" || "$DURATION" == "N/A" ]]; then
                BITRATE_MBPS="0"
            else
                BITRATE=$(echo "scale=0; ($FILE_SIZE * 8) / $DURATION" | bc)
                BITRATE_MBPS=$(echo "scale=2; $BITRATE / 1000000" | bc)
                if [[ "$FFPROBE_FALLBACK_NOTED" -eq 0 ]]; then
                    echo "[INFO] Bitrate calculated from file size (ffprobe returned N/A — normal for DV/AVI)."
                    FFPROBE_FALLBACK_NOTED=1
                fi
            fi
        else
            BITRATE_MBPS=$(echo "scale=2; $BITRATE / 1000000" | bc)
        fi

        if [[ "$DURATION" != "0" && "$DURATION" != "N/A" ]]; then
            DURATION_INT=${DURATION%.*}
            TOTAL_DURATION_SEC=$(( TOTAL_DURATION_SEC + DURATION_INT ))
            DURATION_HMS=$(printf '%d:%02d:%02d' \
                $((DURATION_INT / 3600)) \
                $(((DURATION_INT % 3600) / 60)) \
                $((DURATION_INT % 60)))
        else
            DURATION_HMS="?"
        fi

        # DV NTSC standard is ~25 Mbps video + ~1.5 Mbps PCM audio = ~28.5 Mbps total.
        # Below 28.0 Mbps suggests dropped frames or a degraded passthrough signal.
        if [[ "$BITRATE_MBPS" == "0" ]]; then
            printf "  [???] %-45s  duration=%-9s  bitrate=unknown\n" \
                "$(basename "$AVI_FILE")" "$DURATION_HMS"
            (( WARN_COUNT++ )) || true
        elif (( $(echo "$BITRATE_MBPS < 28.0" | bc -l) )); then
            printf "  [!!!] %-45s  duration=%-9s  bitrate=%s Mbps  LOW\n" \
                "$(basename "$AVI_FILE")" "$DURATION_HMS" "$BITRATE_MBPS"
            (( WARN_COUNT++ )) || true
        else
            printf "  [OK]  %-45s  duration=%-9s  bitrate=%s Mbps\n" \
                "$(basename "$AVI_FILE")" "$DURATION_HMS" "$BITRATE_MBPS"
        fi
    done

    echo "---------------------------------------------------------"

    TOTAL_HMS=$(printf '%d:%02d:%02d' \
        $((TOTAL_DURATION_SEC / 3600)) \
        $(((TOTAL_DURATION_SEC % 3600) / 60)) \
        $((TOTAL_DURATION_SEC % 60)))
    TOTAL_GiB=$(echo "scale=2; $TOTAL_SIZE_BYTES / 1073741824" | bc)
    if [[ "$TOTAL_DURATION_SEC" -gt 0 ]]; then
        OVERALL_MBPS=$(echo "scale=2; ($TOTAL_SIZE_BYTES * 8) / $TOTAL_DURATION_SEC / 1000000" | bc)
    else
        OVERALL_MBPS="N/A"
    fi

    echo "Total duration: ${TOTAL_HMS}  |  Total size: ${TOTAL_GiB} GiB  |  Overall bitrate: ${OVERALL_MBPS} Mbps"
    echo ""
    if [[ "$WARN_COUNT" -eq 0 ]]; then
        echo "[SUCCESS] All ${#AVI_FILES[@]} file(s) passed integrity check."
    else
        echo "[!!!] WARNING: ${WARN_COUNT} file(s) flagged above. Check $LOG_FILE for dropped frames."
        echo "      In passthrough mode low bitrate may indicate a weak A/V input signal"
        echo "      or a TRV330 not fully in passthrough mode."
    fi
    echo "---------------------------------------------------------"
    echo "NOTE: Timecodes in the DV stream are today's wall-clock time"
    echo "      (generated by the TRV330 during A/V conversion)."
    echo "      They are NOT original recording dates from the source tape."
    echo "---------------------------------------------------------"

} | tee -a "$LOG_FILE"

echo "---------------------------------------------------------"
echo "Done."
echo "Log: $LOG_FILE"

} # end main()

main "$@"
